### ISSUE TITLE
Build docker images with npm install --production

### ISSUE THREAD

**Issue by klaszlo** [DigitallySeamless/nodejs-bower-grunt-runtime#2]
I was using your dockerfile to build my yeoman application.
It worked fine, however, the tar.gz result images is 680MB already.

So I would like to modify your Dockerfile, especially this line:
20: ONBUILD RUN npm install

to this:
20: ONBUILD RUN npm install --production

So I downloaded your Dockerfile and replaced the Dockerfile I had and was working.
(The Dockerfile which was working had this one line:
FROM digitallyseamless/nodejs-bower-grunt-runtime
)

Now, when I build my application (docker build -t="myapp" .), the resulted image
do not contain my application. (started with a shell, and the /app dir inside the image is empty).

How can I work with your original dockerfile?
Do the FROM directive in dockerfile starts the actual building?
So do I need to add something at the end of your Dockerfile?

I'm looking forward to your response, and thank you providing this Dockerfile.
It is a great starting point!

**Comment by klaszlo** [comment]
Nevermind, I got it working.

**Comment by kingcody** [comment]
@klaszlo, thanks for the post. One of the reasons for not using the `--production` flag is because the grunt dependencies are needed to build the app inside the docker container. Also, the majority of the space (680mb) taken up by the container is from the underlying base image and operating system layer.

Hope that explains a few things, cheers :)

**Comment by klaszlo** [comment]
kingcody: 
do not worry, I managed to slim down my builds from 624MB to 366MB (exported tar.gz), 
without affecting docker caching mechanism.

My method is to push a docker image to the docker repositories, with devdependencies npm install.

A 366MB image is still managable. I can upload to my server, and start there.

Above 500MB is real PITA for me.

**Comment by kingcody** [comment]
@klaszlo that's awesome,  I'm glad to hear it!

(Yeah I could see > 512Mb being a problem)
